spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/baseball
    username: baseball
    password: baseball
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  application:
    name: baseball

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080
